# Read-only bind helper
x-bind-ro: &bind_ro { type: bind, read_only: true }

# Optional project name (keeps container names tidy)
name: aemsdk

services:
  # Build the Java 17 base once (entrypoint/healthcheck live here)
  aemsdk-base:
    build:
      context: .
      dockerfile: docker/aemsdk/base.Dockerfile
    image: local/aemsdk-base:latest

  aemsdk-author:
    build:
      context: .
      dockerfile: docker/aemsdk/author.Dockerfile
    image: local/aemsdk-author:latest
    depends_on: [ aemsdk-base ]
    profiles: [ "author", "all" ]

    environment:
      RUN_MODE: "author"
      # Container port & AEM listener (keep container fixed unless you know why to change it)
      PORT: "${AEMSDK_AUTHOR_PORT:-5502}"
      JVM_OPTS: "${AEMSDK_JVM_OPTS:--server -Xms3g -Xmx5g -XX:+UseG1GC -Djava.awt.headless=true}"
      AEM_JAR_PATH: "/opt/aem/artifacts/AEM_SDK_Quickstart.jar"
      LICENSE_FILE: "/opt/aem/artifacts/license.properties"

    volumes:
      # Proprietary artifacts (never commit these)
      - <<: *bind_ro
        source: ./artifacts/aem-sdk
        target: /opt/aem/artifacts
      # Persistent repo
      - type: bind
        source: ./data/aemsdk-author
        target: /opt/aem/crx-quickstart

    ports:
      # Host:Container
      - "${AEMSDK_AUTHOR_PORT:-5502}:${AEMSDK_AUTHOR_PORT:-5502}"

    restart: unless-stopped
    stop_grace_period: 3m

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  aemsdk-publish:
    build:
      context: .
      dockerfile: docker/aemsdk/publish.Dockerfile
    image: local/aemsdk-publish:latest
    depends_on: [ aemsdk-base ]
    profiles: [ "publish", "all" ]

    environment:
      RUN_MODE: "publish"
      PORT: "${AEMSDK_PUBLISH_PORT:-5503}"
      JVM_OPTS: "${AEMSDK_JVM_OPTS:--server -Xms3g -Xmx5g -XX:+UseG1GC -Djava.awt.headless=true}"
      AEM_JAR_PATH: "/opt/aem/artifacts/AEM_SDK_Quickstart.jar"
      LICENSE_FILE: "/opt/aem/artifacts/license.properties"

    volumes:
      - <<: *bind_ro
        source: ./artifacts/aem-sdk
        target: /opt/aem/artifacts
      - type: bind
        source: ./data/aemsdk-publish
        target: /opt/aem/crx-quickstart

    ports:
      - "${AEMSDK_PUBLISH_PORT:-5503}:${AEMSDK_PUBLISH_PORT:-5503}"

    restart: unless-stopped
    stop_grace_period: 3m

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

# ---
# Alternative (recommended) port mapping pattern:
# Keep container ports fixed (5502/5503) and vary only host ports.
# This avoids accidental mismatch between AEM's internal listener and host mapping.
#
# Example:
#   environment:
#     PORT: "5502"  # fixed inside container
#   ports:
#     - "${AEMSDK_AUTHOR_PORT:-5502}:5502"
#
# Do this if you need to run multiple authors in parallel on different host ports.
